// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPELHkN6Y__rMFtO_JM-JJDfXmybZuk6E',
    appId: '1:659987796523:web:3c5debc41119c79a92d06e',
    messagingSenderId: '659987796523',
    projectId: 'chatapp-a0ce8',
    authDomain: 'chatapp-a0ce8.firebaseapp.com',
    storageBucket: 'chatapp-a0ce8.appspot.com',
    measurementId: 'G-JVL0S8Q7CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARDJKjTTC2gSb2M-S_o3XetSUTSiu-ih0',
    appId: '1:659987796523:android:24d82501697411b392d06e',
    messagingSenderId: '659987796523',
    projectId: 'chatapp-a0ce8',
    storageBucket: 'chatapp-a0ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNrG4Rz5-sRCbOyETtyoZ_U839jpZy4ck',
    appId: '1:659987796523:ios:74aec393ca8cb47e92d06e',
    messagingSenderId: '659987796523',
    projectId: 'chatapp-a0ce8',
    storageBucket: 'chatapp-a0ce8.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNrG4Rz5-sRCbOyETtyoZ_U839jpZy4ck',
    appId: '1:659987796523:ios:74aec393ca8cb47e92d06e',
    messagingSenderId: '659987796523',
    projectId: 'chatapp-a0ce8',
    storageBucket: 'chatapp-a0ce8.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPELHkN6Y__rMFtO_JM-JJDfXmybZuk6E',
    appId: '1:659987796523:web:32ecdcc26202cb0392d06e',
    messagingSenderId: '659987796523',
    projectId: 'chatapp-a0ce8',
    authDomain: 'chatapp-a0ce8.firebaseapp.com',
    storageBucket: 'chatapp-a0ce8.appspot.com',
    measurementId: 'G-L5DC496DJ2',
  );
}
